// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8YPnMsUvrM8fEmliuyud4sHWBM2ye4M',
    appId: '1:197936576247:web:e916dad04ebe275ddf05f2',
    messagingSenderId: '197936576247',
    projectId: 'foodie-app-5b838',
    authDomain: 'foodie-app-5b838.firebaseapp.com',
    storageBucket: 'foodie-app-5b838.appspot.com',
    measurementId: 'G-YYPWWN852W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT11Hk1BKUCnAhyS-ivOewXfYcwost4pg',
    appId: '1:197936576247:android:e11c61e3b289e238df05f2',
    messagingSenderId: '197936576247',
    projectId: 'foodie-app-5b838',
    storageBucket: 'foodie-app-5b838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQRf-R_qy6A-4AcanUTL3if7k_Al--uw',
    appId: '1:197936576247:ios:1aaebacf1bcc23dadf05f2',
    messagingSenderId: '197936576247',
    projectId: 'foodie-app-5b838',
    storageBucket: 'foodie-app-5b838.appspot.com',
    iosBundleId: 'com.example.myfinalprojecthackton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQRf-R_qy6A-4AcanUTL3if7k_Al--uw',
    appId: '1:197936576247:ios:1aaebacf1bcc23dadf05f2',
    messagingSenderId: '197936576247',
    projectId: 'foodie-app-5b838',
    storageBucket: 'foodie-app-5b838.appspot.com',
    iosBundleId: 'com.example.myfinalprojecthackton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa8YPnMsUvrM8fEmliuyud4sHWBM2ye4M',
    appId: '1:197936576247:web:bd3cfc2d8303e6c0df05f2',
    messagingSenderId: '197936576247',
    projectId: 'foodie-app-5b838',
    authDomain: 'foodie-app-5b838.firebaseapp.com',
    storageBucket: 'foodie-app-5b838.appspot.com',
    measurementId: 'G-FLGTCSZLSV',
  );
}
